changelog:
    exclude:
        labels:
            - ignore-for-release
        authors:
            - octocat
    categories:
        - title: Breaking Changes ⚠️
          labels:
              - breaking-change
        - title: Exciting New Features 🎉
          labels:
              - enhancement
        - title: Fixes 🐛
          labels:
              - bug
        - title: Technical Changes 🛠
          labels:
              - technical
