name: 🚀 Feature request
description: Suggest an idea for this project
title: "[Feature]: <title>"
labels: ["enhancement"]
body:
    - type: checkboxes
      attributes:
          label: Requirements
          options:
              - label: I have updated the Strategy Pack to the latest available version
                required: true
              - label: I did a search to see if there is a similar issue or if a pull request is open.
                required: true
    - type: textarea
      attributes:
          label: Is your feature request related to a problem?
          description: >
              A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
      validations:
          required: false
    - type: textarea
      attributes:
          label: Describe the feature or solution you'd like
          description: >
              A clear and concise description of what you want to happen.
      validations:
          required: true
