anchors:
    - actions-info: &actions-info-ref
          tap_action:
              action: more-info
          icon_tap_action:
              action: none
          hold_action:
              action: more-info
    - actions-toggle: &actions-toggle-ref
          tap_action:
              action: toggle
          icon_tap_action:
              action: none
          hold_action:
              action: more-info
    - simple-tile: &simple-tile-ref
          hide_state: true
          color: primary

minColumnWidth: 200
tabs:
    - title: Control
      icon: mdi:button-pointer
      rows:
          - title: Alarm
            card:
                type: tile
                entity: $entity
                features:
                    - type: alarm-modes
                      modes:
                          - armed_home
                          - armed_away
                          - armed_night
                          - armed_vacation
                          - armed_custom_bypass
                          - disarmed
                <<: *actions-info-ref
            filter:
                include:
                    - type: domain
                      value: alarm_control_panel
          - title: Media
            card:
                type: custom:mushroom-media-player-card
                entity: $entity
                use_media_artwork: true
                show_volume_level: true
                use_media_info: false
                collapsible_controls: true
                volume_controls:
                    - volume_set
                media_controls:
                    - play_pause_stop
                <<: *actions-toggle-ref
            filter:
                include:
                    - type: domain
                      value: media_player
          - title: Light
            card:
                type: tile
                entity: $entity
                features:
                    - type: light-brightness
                    - type: light-color-temp
                <<: *actions-toggle-ref
            filter:
                include:
                    - type: domain
                      value: light
          - title: Fan
            card:
                type: tile
                entity: $entity
                features:
                    - type: fan-speed
                    - type: fan-preset-modes
                      style: icons
                <<: *actions-toggle-ref
            filter:
                include:
                    - type: domain
                      value: fan
          - title: Humidifier
            card:
                type: tile
                entity: $entity
                features:
                    - type: target-humidity
                    - type: humidifier-toggle
                <<: *actions-toggle-ref
            filter:
                include:
                    - type: domain
                      value: humidifier
          - title: Cover
            card:
                type: tile
                entity: $entity
                features:
                    - type: cover-open-close
                <<: *actions-info-ref
            filter:
                include:
                    - type: domain
                      value: cover
          - title: Vacuum
            card:
                type: tile
                entity: $entity
                features:
                    - type: vacuum-commands
                      commands:
                          - start_pause
                          - return_home
                <<: *actions-info-ref
            filter:
                include:
                    - type: domain
                      value: vacuum
          - title: Switch
            card:
                type: tile
                entity: $entity
                <<: [*simple-tile-ref, *actions-toggle-ref]
                color: amber
            filter:
                include:
                    - type: domain
                      value: switch
                    - type: domain
                      value: input_boolean
          - title: Select
            card:
                type: tile
                entity: $entity
                features:
                    - type: select-options
                <<: [*simple-tile-ref, *actions-info-ref]
            filter:
                include:
                    - type: domain
                      value: select
                    - type: domain
                      value: input_select
          - title: Button
            card:
                type: tile
                entity: $entity
                <<: [*simple-tile-ref, *actions-toggle-ref]
            filter:
                include:
                    - type: domain
                      value: button
                    - type: domain
                      value: scene
          - title: Number
            card:
                type: tile
                entity: $entity
                features:
                    - type: numeric-input
                      style: slider
                <<: [*simple-tile-ref, *actions-info-ref]
            filter:
                include:
                    - type: domain
                      value: number
    - title: Stats
      icon: mdi:chart-line
      rows:
          - title: Alert
            card:
                type: tile
                entity: $entity
                <<: [*simple-tile-ref, *actions-info-ref]
            filter:
                include:
                    - type: domain
                      value: binary_sensor
                exclude:
                    - type: attribute
                      value:
                          key: device_class
                          value: motion
                    - type: attribute
                      value:
                          key: device_class
                          value: occupancy
          - title: Sensor
            card:
                type: tile
                entity: $entity
                <<: [*simple-tile-ref, *actions-info-ref]
                hide_state: false
            filter:
                include:
                    - type: domain
                      value: sensor
                exclude:
                    - type: attribute
                      value:
                          key: device_class
                          value: battery
                    - type: state
                      comparator: is_numeric
          - title: Graphs
            card:
                type: custom:mini-graph-card
                entities:
                    - $entity
                align_header: left
                align_icon: left
                align_state: center
                font_size: 50
                font_size_header: 12
                <<: *actions-info-ref
            filter:
                include:
                    - type: domain
                      value: sensor
                    - type: state
                      comparator: is_numeric
                exclude:
                    - type: attribute
                      value:
                          key: device_class
                          value: battery
