name: Build
on:
    pull_request:
    push:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build
