name: HACS validation
on:
    pull_request:
    push:
jobs:
    hacs:
        name: HACS Action
        runs-on: "ubuntu-latest"
        steps:
            - name: HACS Action
              uses: "hacs/action@main"
              with:
                  category: "plugin"
