name: Pull Request Labels
permissions:
    issues: read
    pull-requests: write
on:
    pull_request_target:
        types:
            - opened
            - edited
            - reopened
            - synchronize
jobs:
    label:
        runs-on: ubuntu-latest
        steps:
            - uses: nearform-actions/github-action-check-linked-issues@v1
              id: check-linked-issues
            - name: Get the output
              run: |
                  if ${{ steps.check-linked-issues.outputs.linked_issues_count }} == 0 ; then
                    echo "You need to have at least one linked issue!"
                    exit 1
                  fi
            - uses: mondeja/remove-labels-gh-action@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  labels: |
                      breaking-change
                      enhancement
                      bug
            - name: Copy Labels
              uses: michalvankodev/copy-issue-labels@v1.2.1
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  custom-keywords: |
                      enhancement
                      bug
            - name: RegEx Issue Labeler
              uses: github/issue-labeler@v3.4
              with:
                  repo-token: ${{ github.token }}
                  configuration-path: .github/labeler.yml
                  enable-versioned-regex: 0
