name: Release
permissions:
    contents: write
on:
    push:
        tags:
            - "*.*.*.beta.*"
            - "*.*.*"
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build
            - name: Release Beta
              uses: softprops/action-gh-release@v2
              if: ${{ contains(github.ref, 'beta') }}
              with:
                  prerelease: true
                  make_latest: false
                  generate_release_notes: true
                  files: dist/*.js
                  fail_on_unmatched_files: true
            - name: Release
              uses: softprops/action-gh-release@v2
              if: ${{ ! contains(github.ref, 'beta') }}
              with:
                  prerelease: false
                  make_latest: true
                  generate_release_notes: true
                  files: dist/*.js
                  fail_on_unmatched_files: true
